version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_storage:/home/node/.n8n
    restart: always

volumes:
  n8n_storage:
